# Generated by Django 4.2.16 on 2024-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposting',
            name='comment',
            field=models.CharField(default=1234, max_length=300),
            preserve_default=False,
        ),
    ]
